### ISSUE TITLE
Provide styling for Markdown content in sections

### ISSUE THREAD

**Issue by dbellomo** [ttntm/11ty-landing-page#3]
full markdown processing don't work on sections.
e.g,
can't processing "#" and ">" tags

**Comment by ttntm** [comment]
I don't see anything wrong with Markdown processing:

![Screenshot from 2021-10-06 11-17-08](https://user-images.githubusercontent.com/41571384/136175195-0363db18-e1bd-4299-b417-868f468986e3.png)

All tags input into `sections/about.md` render as respective HTML elements.

In conclusion: this is a styling issue rathern than a functional limitation.

What's left to do:

1. Add a custom class (i.e. `md-content`) to line 6 in `./src/includes/section.about.njk`
2. Write some CSS targeting the children of this class and put it at the bottom of `./src/inludes/css/custom.css`

I'll see when I can get around to doing that, pull requests would be much appreciated though.
