### ISSUE TITLE
Please provide any screenshot or demos 

### ISSUE THREAD

**Issue by xXWarMachineRoXx** [ttntm/11ty-landing-page#4]
@ttntm Please provide any screenshot or demos so as to better judge whether its worth the time or not.

thanks and regards,
xxwarmachineroxx

**Comment by ttntm** [comment]
A link to a fully functional demo can be found in the repo's description:

![image](https://github.com/ttntm/11ty-landing-page/assets/41571384/f8673096-f88c-4479-9f8e-a18970b6f4fe)

Here it is again for convenience: https://awesome11ty.ttntm.me/
